spring:
   mail:
      default-encoding: UTF-8
      host: smtp.gmail.com
      port: 587
      username: ie307viendict@gmail.com
      password: deoztrmviqhmdtjp
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
            debug: true
      test-connection: false
      protocol: smtp